### PR TITLE
backbone.js with vert.x

### PR DESCRIPTION
**Pull request by ohneda**
Hi,

I added new sample app which demonstrates a real-time application using Vert.x and its eventbus, based on  Option 1 refering to Option 7.
This sample app work in the same way as Option 7.

The modification I did on Option 1 is very simple, just added custom_sync.js that overwrite Bacbone.sync  to send a message on the eventbus, and some scripts in script.js to receive a message and trigger events to sync collections with backend.

I'm not sure if it is useful or not, but Vert.x is so powerful and simple next generation (Node.js alternative) framework that I believe the sample might be helpful for someone who are interested in using Vert.x and Backbone.js together.

Let me know if there are any problems or questions.

Thanks.

Yuichi

### CODE REVIEW

**Comment by addyosmani** [comment]
Thanks for sending this through @ohneda. I've just been reading up on https://github.com/purplefox/vert.x and it looks interesting. Once I've had a chance to test your PR through thoroughly I'll be happy to merge it.

**Comment by addyosmani** [comment]
@ohneda Have there been a great deal of changes to https://github.com/vert-x/vert.x since this PR was made? I'd be happy to do a merge if you think the implementation/setup is still relevant.

**Comment by ohneda** [comment]
Hi Addy,

Thank you for the reply.
I've updated my sample app to the latest version 1.2.3 of Vert.x, using new module system and modified some codes to reflect the changes to event bus.

Glad if you could check out.

**Comment by addyosmani** [comment]
@ohneda Thank you! :) I really appreciate the effort you've put into updating this. One final ask: could you add a commit to update the main readme file with your entry? This would be Boilerplate 8. I'm happy to do it myself, but usually ask authors to so they can get their name etc in there too. Cheers!

**Comment by ohneda** [comment]
okay, I did it!

**Comment by addyosmani** [comment]
Perfect! Thanks! :)

**Pull request merged**
